name: proyectofinal
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.12.1
  flutter_dotenv: ^5.0.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/foto_aaron.jpg
    - lib/assets/Andy_Foto.jpg
    - lib/assets/defensa1.jpg
    - lib/assets/defensa2.jpg
    - lib/assets/defensa3.jpg

  uses-material-design: true
